name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # install nix
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: devenv
        extraPullNames: nix-community
  
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: Build
      run: devenv shell cargo build --verbose

    - name: Run tests
      run: devenv shell cargo test --verbose
